# permissions for end users to edit halayersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: halayerset-editor-role
rules:
- apiGroups:
  - ha-sno.medik8s.io
  resources:
  - halayersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ha-sno.medik8s.io
  resources:
  - halayersets/status
  verbs:
  - get
