# permissions for end users to view halayersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: halayerset-viewer-role
rules:
- apiGroups:
  - ha-sno.medik8s.io
  resources:
  - halayersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ha-sno.medik8s.io
  resources:
  - halayersets/status
  verbs:
  - get
